default: &default
  adapter: postgresql
  database: interview_project
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: localhost


development:
  <<: *default
  database: interview_project_development
  username: postgres
  password:

test:
  <<: *default
  database: interview_project_test
  username: postgres
  password:

production:
  <<: *default
